[project]
authors = ["Florian Wilhelm <florian.wilhelm@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "flairs25-gender-independence"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
scipy = ">=1.14.1,<2"
numpy = ">=2.2.1,<3"
pip = ">=24.3.1,<25"
jupyterlab = ">=4.3.4,<5"
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.2.3,<3"
tqdm = ">=4.67.1,<5"
